apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "smart.fullname" . }}-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.storageSize }}
