# -----------------------------------------------------------------------------
# Kubernetes Secret for PostgreSQL credentials in the "smart" application.
#
# This template:
# - Creates an Opaque secret containing the PostgreSQL user's password.
# - The password is sourced from `.Values.postgresql.password`.
# - This secret is referenced by the Postgres Deployment for authentication.
#
# Note: `stringData` is used to simplify value input without requiring base64.
# -----------------------------------------------------------------------------

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "smart.fullname" . }}-postgres-secret
type: Opaque
stringData:
  password: {{ .Values.postgresql.password | quote }}
