apiVersion: v1
kind: Service
metadata:
  name: {{ include "smart.fullname" . }}
  labels:
    {{- include "smart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "smart.selectorLabels" . | nindent 4 }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "smart.fullname" . }}-postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: {{ include "smart.name" . }}-postgres
