# -----------------------------------------------------------------------------
# Kubernetes ServiceAccount for the "smart" application.
#
# This template:
# - Conditionally creates a ServiceAccount if `.Values.serviceAccount.create` is true.
# - Uses `.Values.serviceAccount.annotations` if provided.
# - Sets `automountServiceAccountToken` based on `.Values.serviceAccount.automount`.
#
# ServiceAccounts are useful for granting pods permissions via RBAC,
# for example, when interacting with the Kubernetes API or external cloud services.
# -----------------------------------------------------------------------------

{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "smart.serviceAccountName" . }}
  labels:
    {{- include "smart.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
