# -----------------------------------------------------------------------------
# Kubernetes TLS Secret for the "smart" application.
#
# This template:
# - Conditionally creates a TLS secret if `.Values.tls.enabled` is true.
# - Encodes the certificate and private key in base64 using Helm's `b64enc`.
# - Uses type `kubernetes.io/tls`, which Kubernetes expects for TLS usage.
# - Intended to be used with Ingress TLS configurations.
#
# Note: `.Values.tls.crt` and `.Values.tls.key` must be plain text strings
# containing the certificate and private key respectively.
# -----------------------------------------------------------------------------

{{- if .Values.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "smart.fullname" . }}-tls-secret
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.crt | b64enc }}
  tls.key: {{ .Values.tls.key | b64enc }}
{{- end }}
