name: cd_ci

on:
  pull_request:
  push:
    branches: [gurpreet]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv sync
      - name: Test with pytest
        run: pipenv run python -m pytest

  docker:
    runs-on: ubuntu-latest
#    needs: [test]
    steps:
      - uses: actions/checkout@v4
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      # - run : |
      #     mkdir -p ~/.gsutil
      #     echo "${{ secrets.GCP_CREDS }}" > ~/.gsutil/credstore2
      - name: Docker Login
        run:  gcloud auth configure-docker gcr.io --quiet
      # - name: Build Data Pipeline
      #   run: |
      #     docker build -t gcr.io/smart-452816/datapipeline:${GITHUB_SHA::7} ./src/datapipeline
      #     docker push gcr.io/smart-452816/datapipeline:${GITHUB_SHA::7}
      - name: Build Frontend
        run: |
          docker build -t gcr.io/smart-452816/frontend:${GITHUB_SHA::7} ./src/frontend
          docker push gcr.io/smart-452816/frontend:${GITHUB_SHA::7}

  deploy:
    runs-on: ubuntu-latest
#    needs: [docker]
    steps:
      - uses: actions/checkout@v4
      - run : |
          mkdir -p ~/.gsutil
          echo "${{ secrets.GCP_CREDS }}" > ~/.gsutil/credstore2
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: 'smart-cluster'
          location: 'us-central1-a'

      # The KUBECONFIG env var is automatically exported and picked up by kubectl.
      - id: 'get-pods'
        run: 'kubectl get pods'

      - name: 'Helm Install'
        run: 'helm install smart ./helm --set image.tag=${GITHUB_SHA::7}'
