name: cd_ci

on:
  pull_request:
  push:
    branches: [gurpreet]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv sync
      - name: Test with pytest
        run: pipenv run python -m pytest

  docker:
    runs-on: ubuntu-latest
#    needs: [test]
    steps:
      - uses: actions/checkout@v4
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - name: Build Data Pipeline
        run: docker build -t us-west1-docker.pkg.dev/${{ PROJECT_ID }}/${{ GCR_REPO }}/datapipeline:${GITHUB_SHA::7} ./src/datapipeline
      # - name: Build API
      #   run: docker build -t us-west1-docker.pkg.dev/${{ PROJECT_ID }}/${{ GCR_REPO }}/api:${GITHUB_SHA::7} ./src/api
      - name: Build Frontend
        run: docker build -t us-west1-docker.pkg.dev/${{ PROJECT_ID }}/${{ GCR_REPO }}/frontend:${GITHUB_SHA::7} ./src/frontend

  deploy:
    runs-on: ubuntu-latest
#    needs: [docker]
    steps:
      - uses: actions/checkout@v4
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'
