name: cd_ci

on:
  pull_request:
  push:
    branches: [gurpreet]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv sync
      - name: Test with pytest
        run: pipenv run python -m pytest

  deploy:
    runs-on: ubuntu-latest
    depends-on: test
    steps:
      - uses: actions/checkout@v4
      - name: Build Data Pipeline
        run: docker build -t datapipeline ./src/datapipeline
      - name: Build API
        run: docker build -t api ./src/api
      - name: Build Frontend
        run: docker build -t frontend ./src/frontend
